server:
  port: 8088
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: mycert
  servlet:
    Session:
      timeout: 15m
  error:
    whitelabel:
      enabled: false  
    path: /error  

spring:
    thymeleaf:
        cache: false
    application:
        name: statuswave
    datasource:
        url: jdbc:postgresql://localhost:5432/statuswave
        username: sa
        password: passpgsql
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: false
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
hCaptcha:
  secret:
    key: ${H_CAPTCHA_SECRET}       